hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_airline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_alert_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_autolpn_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_case_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_certificate_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_company_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_domic_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_hotel_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_house_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_imei_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_imsi_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_internetbar_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_jail_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_law_docment_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_package_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_phonenumber_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_qq_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_school_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_sina_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_trainline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/vertex_wechat_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_accusercom_link_doc_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_alert_link_case_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_case_link_autolpn_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_case_reportby_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_case_victim_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_com_lawsuit_com_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_com_loan_com_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_com_shareholder_com_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_company_workmate_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_defendantcom_link_doc_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_common_father_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_common_grand_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_common_greatgrand_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_common_mother_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_common_parent_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_grandparents_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_find_greatgrands_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_groupcall_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_groupmsg_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_arrived_airline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_attend_school_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_checkin_airline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_fatheris_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_guardianis_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_kinsfolk_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
#hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_legal_com_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_link_certificate_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_link_phone_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_link_qq_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_link_sinablog_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_link_wechat_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_live_house_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_motheris_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_open_phone_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_own_autolpn_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_own_house_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_rent_house_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_reserve_airline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_reserve_trainline_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_same_order_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_smz_phone_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_spouse_person_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_stay_hotel_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_stay_jds_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_stay_kss_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_surfing_internetbar_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_with_airline_travel_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_with_internetbar_surfing_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_with_trainline_travel_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_person_work_com_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_call_alert_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_link_qq_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_link_sinablog_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_link_wechat_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_receive_package_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_send_package_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phone_sendpackage_phone_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phonenumber_use_imei_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_phonenumber_use_imsi_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_qq_link_qq_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/edge_same_hotel_house_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
hadoop distcp -m 30 -i /phoebus/_fileservice/users/slmp/shulianmingpin/jg_data/relation_score_res_jg hdfs://24.1.17.4:8020/user/shulian/graph_data/jg_data_standby/
